name: GitHub Actions Demo
on:
  # 1) Every push to main, except when ONLY files under .github/ changed
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  # 2) On every pull request with main as the base branch
  pull_request:
    branches: [ main ]
  # 3) Every Sunday at 06:15 UTC
  schedule:
    - cron: '15 6 * * 0'  # minute hour day month day-of-week (0 = Sunday)
  # 4) Manually via the GitHub UI / API
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
